url: "https://blog.johnny.moe/doge-university"
geomtop: "RTG_geomtop"

name: DOGE University
description: Official website of DOGE University, where academic excellence meets innovative crypto culture.

markdown: kramdown
# kramdown:
  # math_engine: nil

highlighter: rouge

excerpt_separator: <!--more-->

paginate: 24
paginate_path: "allnews/page:num"
permalink: /:year/:month/:title/

new_seminars_label: Upcoming seminars

defaults:
  - scope:
      path: ""
      type: departmentpeople
    values:
      layout: departmentpeople_page
      nav_parent: People

collections:
  departmentpeople:
    output: true
    permalink: /people/:name/

exclude: [vendor]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

author: DOGE University

feed:
  path: /feed.xml
